### ISSUE TITLE
Feature: support for @ionic/schematics-angular

### ISSUE THREAD

**Issue by cyrilletuzi** [cyrilletuzi/vscode-angular-schematics#10]
Ionic 4 now relies on Angular schematics and could be added to the list of default schematics supported.

Depends on #8. Would be better with #9.

@jgw96 can you confirm that Ionic just add some `schematics` (like `page`), but the other classic ones (like `component`) are the same as in Angular CLI? So `ionic g component` produces the same result as `ng g component`?

**Comment by dwieeb** [comment]
Hi @cyrilletuzi 👋 

I made `@ionic/schematics-angular`. The package can be found in the CLI repo: https://github.com/ionic-team/ionic-cli/tree/master/packages/%40ionic/schematics-angular

You'll notice in our [`collection.json`](https://github.com/ionic-team/ionic-cli/blob/master/packages/%40ionic/schematics-angular/collection.json) we extend all the existing Angular schematics as well as add `page`. It's true you can use the Angular CLI to generate all these features. The Ionic CLI shells out to the Angular CLI for this, actually. This is all possible when the `defaultCollection` is set: https://github.com/ionic-team/starters/blob/master/angular/base/angular.json#L168 OR when you use the collection name when generating components, e.g. `ng generate @ionic/schematics-angular:page PageName`

**Comment by cyrilletuzi** [comment]
Thanks @dwieeb. So I need to code support for aliases and defaultCollection and it'll be good.

**Comment by cyrilletuzi** [comment]
Done in v1.5.

@jgw96 @dwieeb
