### ISSUE TITLE
Cannot generate on right click in workspace view

### ISSUE THREAD

**Issue by hegedis-andor** [cyrilletuzi/vscode-angular-schematics#110]
In vs code there is an option to add folder to workspace which simplifies the explorer by adding only the folders which are frequently used, but if i wan to generate anything by right click on a folder and choosing generate *, than it does not do anything.

**Comment by cyrilletuzi** [comment]
Multi-root workspaces is already supported by this extension (it's mentioned in the README). And did a check: it's working both on Mac and Windows.

So I'll need a reproduction and more info to able to help you, especially:
- your OS,
- your VS Code version,
- did you check the requirements in README, especially the one about opening the project at root?
- does it work when you have just one workspace?

**Comment by cyrilletuzi** [comment]
Closing for house-keeping, as there is no news. Feel free to comment and I'll reopen the issue.

**Comment by cyrilletuzi** [comment]
For info: v4 has just been released and is a full rewrite of the extension. It should have fixed any weird case like this one.

It took more than a *full-time* non-paid week to do this rewrite. Yet I still do not have any **[sponsor](https://github.com/sponsors/cyrilletuzi)**. So please consider to help, or to ask your enterprise, which makes money with this extension, to help.
