### ISSUE TITLE
Need to disable/enable the plugin to make it work.

### ISSUE THREAD

**Issue by alavaros** [cyrilletuzi/vscode-angular-schematics#129]
This happens very often, when I want to create a new component or service, I can't find the option in the context menu, and I have to disable and enable the plugin to make it appear again.

**Comment by cyrilletuzi** [comment]
Your issue is far too vague to be able to help. However, v4 will be released soon and is a full rewrite of the extension. Can you test with instructions in #125?

**Comment by cyrilletuzi** [comment]
For info: v4 has just been released and is a full rewrite of the extension. So I'll close this issue, as things that were happening in v3 are not relevant in v4. If there still is an issue with v4, please open a new issue.
