### ISSUE TITLE
@angular/material@6.4.7 schematics doesn't seem to be working

### ISSUE THREAD

**Issue by ErnestUTN** [cyrilletuzi/vscode-angular-schematics#13]
As I currently only have @angular/material@6.4.7 installed in my project, I can't say the same for the other default supported schematics.

Steps to reproduce bug:

1- Either  right-click or the schematics view or the command palette,
2- Select nav from @angular/material
3- Nothing happens (the command pallete doesn't show up with any option nor components or files are created

![image](https://user-images.githubusercontent.com/8976434/45004078-a19f8300-afbf-11e8-934f-f1142aff92fb.png)

4- It works with the CLI commands though:

![image](https://user-images.githubusercontent.com/8976434/45004091-c693f600-afbf-11e8-8fa1-3407882a857a.png)

**Comment by cyrilletuzi** [comment]
There was already an issue with Material schematics (#5), I suppose they broke things again... I'll investigate as soon as possible.

**Comment by cyrilletuzi** [comment]
This one was not Material fault. :D Previous performance improvements in the extension introduced an issue where the schematics path was not correctly saved in some scenarios. A fix has been released (v1.6.2).

Thanks for reporting the issue @ErnestUTN. Feel free to star this repo and the extension on the VS Code Marketplace. 👍

**Comment by ErnestUTN** [comment]
Many thanks sir. I will do :+1:
