### ISSUE TITLE
Allow to customize shell that extension uses for calling angular-cli

### ISSUE THREAD

**Issue by pupizoid** [cyrilletuzi/vscode-angular-schematics#16]
Hi!

This is amasing extension, but I've found one problem using it. It uses `/bin/sh` as a default shell to call angular-cli binary. The problem comes from I'm using `zsh` as my default shell and it's configured to know where `ng` binary is located but not the `/bin/sh`, so extension prints an error when i'm trying to create any object:
```
ng g @angular/material:table ldap
/bin/sh: ng: command not found
```

Can you add option to settings to customize used shell?

**Comment by cyrilletuzi** [comment]
@pupizoid An earlier version of the extension was using the VS Code terminal to launch the CLI commands, which I think would use your custom shell. Problem was the Terminal API for extensions was too limited (you can't know the result of the command for example). Last versions of VS Code introduced improvements to the Terminal API but I didn't check in details.

So now the extension is using the native `exec` from Node. So yes, it should be possible to add an option to configure this behavior. But it would be even better to auto-detect it: could you confirm that your shell path is configured somewhere in the VS Code settings?

**Comment by cyrilletuzi** [comment]
@pupizoid Can you test with [this beta](https://github.com/cyrilletuzi/vscode-angular-schematics/raw/shell/angular-schematics-1.8.0-beta.0.vsix)?

It should auto-detect your shell.

Btw, do you think auto-detecting shell args is relevant for this extension or not?

**Comment by pupizoid** [comment]
@cyrilletuzi, thanks for quick answer! I've just tested beta and it works as expected, awesome! 

I've found following setting:
```json
{
    "terminal.integrated.shell.linux": "/bin/zsh",
    "terminal.integrated.shell.osx": "/bin/zsh"
}
```
I think auto-detecting shell will be enought for most cases of usage, but it would be better to have ability to set path to shell manually as an optional parameter.

**Comment by cyrilletuzi** [comment]
@pupizoid Ability to change the shell manually is already managed by VS Code directly, via the settings you just quoted.

Do you know if shell args are relevant to this extension too?

**Comment by pupizoid** [comment]
@cyrilletuzi, from [here](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration), shell args seems to be specific to the shell launch and not to the other processes runned by this shell. But in case when user want to set integrated shell that requires specific args it would be good to allow setting args too.

**Comment by cyrilletuzi** [comment]
Fixed in v1.8.

As I'm not sure how to manage shell args the right way, and as it doesn't seem important for this extension, v1.8 doesn't manage shell args. We'll see if someone open an issue about this.

**Comment by cyrilletuzi** [comment]
@pupizoid Thanks for the issue and testing. Don't forget to leave stars on [VS Code marketplace](https://marketplace.visualstudio.com/items?itemName=cyrilletuzi.angular-schematics). 👍

**Comment by cyrilletuzi** [comment]
@pupizoid Can you check it still works with v1.8.1? I had to release a patch to only allow custom shell on macOS and Linux (it was failing on Windows). Thanks.

**Comment by cyrilletuzi** [comment]
@pupizoid Thanks again for testing. I'll keep this open until I have time to investigate about Windows.

**Comment by cyrilletuzi** [comment]
I'll close this issue as it's fixed for macOs and Linux, where it makes sense.

Custom shell on Windows doesn't seem to be a common scenario, but if someone was to be concerned, please open a new issue.
