### ISSUE TITLE
support use case for primeng-schematics

### ISSUE THREAD

**Issue by doggy8088** [cyrilletuzi/vscode-angular-schematics#17]
I was trying [primeng-schematics](https://www.npmjs.com/package/primeng-schematics) with the Angular Schematics today.  I realized that they MUST accept `--name` option to generate a component.  Angular Schematics is unable to skip the NAME parameter at this time.  I have to input a fake name in order to generate a component successfully.

I also have a suggestion for [primeng-schematics](https://github.com/andriy101/primeng-schematics) for change a bit to support the common use case for optional `--name` option.  See also: https://github.com/andriy101/primeng-schematics/issues/2

**Comment by cyrilletuzi** [comment]
Thanks for reporting this issue. As each schematic can do what it wants, it's quite hard for this extension to manage all cases. I'll check the `primeng-schematics`, correct the issues and add it to the default list.

**Comment by cyrilletuzi** [comment]
This is not (yet) official schematics for PrimeNG. Do you know if the author is related to the PrimeNG team?

If those schematics are not official, as they are really new, I'll wait a little to see how it goes and that it fixes is own issues.

**Comment by cyrilletuzi** [comment]
@doggy8088 OK, I'll let the issue opened, let me know when official schematics for PrimeNG are released. I'll add them in the default list.

**Comment by cyrilletuzi** [comment]
Depends on primefaces/primeng#6187

**Comment by cyrilletuzi** [comment]
Closing this one for now as the Prime team doesn't show any sign about this lately. Should Prime schematics be added, they will be added in this extension.

**Comment by doggy8088** [comment]
@cyrilletuzi It may release in [7.0.1 hopefully](https://twitter.com/cagataycivici/status/1065928827786932225).

**Comment by andriy101** [comment]
Hello @cyrilletuzi  and @doggy8088, I really appreciate your feedbacks regarding my Primeng Schematics module. I am not related to official prime ng team. I will try to fix / approve / check approvements proposed by @doggy8088. Also I want to upgrade packages to 7th version and add new c-prompts. Thanks again
