### ISSUE TITLE
Missing 'force' option on @ngrx/schematics commands

### ISSUE THREAD

**Issue by ianhlavats** [cyrilletuzi/vscode-angular-schematics#178]
# Checks before posting an issue

- [X ] I have read all the extension's documentation (README and docs/TROUBLESHOOTING)
- [X ] My project meets the requirements indicated in README
- [ X] I launched `ng g component hello` in the *VS Code* Terminal inside my project, and it works
- [X ] I looked at the extension's logs ("Angular Schematics" Output channel, second tab left to the Terminal), and tried to fix my project's configuration accordingly
- [X ] I understand I am writing to a *human being*, doing this open source project on his *free* time
- [X ] I will be involved in my own issue, by answering questions and informing if the issue is resolved

# Configuration

- VS Code version: 
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

- Angular version (`ng version`):
```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.7
Node: 10.18.1
OS: darwin x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: No

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.7
@angular-devkit/build-angular      0.901.7
@angular-devkit/build-ng-packagr   0.901.7
@angular-devkit/build-optimizer    0.901.7
@angular-devkit/build-webpack      0.901.7
@angular-devkit/core               9.1.7
@angular-devkit/schematics         9.1.7
@angular/cli                       9.1.7
@ngtools/webpack                   9.1.7
@schematics/angular                9.1.7
@schematics/update                 0.901.7
ng-packagr                         9.1.5
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.42.0
```

# Description of the issue

Force option is available on the command line (-f) but is missing in the `@ngrx/schematics` dialog.

# How to reproduce the issue

1. Right-click a folder in an Angular 9 project and choose "Angular: Generate another schematic" > `@ngrx/schematics` > feature (or entity for example).
1. Enter name "foo" for example.
1. Try to select "force" option (it's not there).

**Comment by cyrilletuzi** [comment]
`force` option does not exist in [ngrx schematics](https://github.com/ngrx/platform/blob/master/modules/schematics/src/feature/schema.json), so it may be a global Angular CLI option.

Except for `ng update` (where it makes sense), I never met this option in any CLI documentation or schemas, so it would need some investigation.

Even it is indeed supported, I'm not sure `force` should be encouraged. What is your use case?

**Comment by ianhlavats** [comment]
Hi @cyrilletuzi ,

When I run `ng generate @ngrx/schematics:feature --help` I can see the force option:

![image](https://user-images.githubusercontent.com/3005952/84074504-f9f48780-a9d2-11ea-8c48-23680e3dbc74.png)

My use case is like this:

1. Generate feature state
1. Add Entity state (this requires overwriting some files generated by feature state schematic)

Without the force option the command will fail so I am unable to use the UI to run the schematic and have to use the command line.

I would prefer to use the UI ... coming from a Webstorm background their implementation of Angular CLI schematics supports the force option for this scenario so I would really like to see it supported in Visual Studio Code too!

Regards,
Ian

**Comment by cyrilletuzi** [comment]
> Wouldn't it be easier to just pass through all the options?

The extension is already doing that.

I've searched in:
- entity schematic [here](https://github.com/ngrx/platform/tree/master/modules/schematics/src/entity) and [here](https://github.com/ngrx/schematics-builds/blob/master/src/entity/schema.json): no `force` option
- [`ngrx/platform` repo](https://github.com/ngrx/platform/) global `force` search: only 8 occurrences, unrelated
- [`ngrx/schematics-builds` repo](https://github.com/ngrx/schematics-builds/) global `force` search: 0 occurrence
- in npm distributed code (ie. in `node_modules/@ngrx/schematics/src/entity/schema.json`): no `force` option
- [official ngrx doc](https://ngrx.io/guide/schematics/entity): no `force` option
- I even checked the git history in case you use an older version: no success either

So it is normal the extension does not propose it. I have no more time currently to do more search, so if you want to resolve this issue, you'll have to find from where the option comes from.

**Comment by ianhlavats** [comment]
Hi @cyrilletuzi ,

It is documented in the Angular CLI as an option to the `ng generate` command itself, not part of the schematic _per se_:

> --force=true\|false | When true, forces overwriting of existing files.Default: false
https://angular.io/cli/generate

Can these options be added manually to your tool's interface?

Regards,
Ian

**Comment by cyrilletuzi** [comment]
Added in 4.2.0.

For info: v4 took me more than a *full-time* non-paid week to do. Yet I still do not have any **[sponsor](https://github.com/sponsors/cyrilletuzi)**. So please consider to help, or to ask your enterprise, which makes money with this extension, to help.

**Comment by ianhlavats** [comment]
Thank you @cyrilletuzi !
