### ISSUE TITLE
Feature: add a button to auto scan for schematics

### ISSUE THREAD

**Issue by doggy8088** [cyrilletuzi/vscode-angular-schematics#18]
I know there is a `"ngschematics.schematics": []` setting for add other schematics.  What if these packages can be detected automatically if these schematics package are already exists in `package.json` file?

**Comment by cyrilletuzi** [comment]
`package.json` is not enough to know which packages contain Angular schematics or not. It would need to scan all the `node_modules` directories, and as explained by the README it would be too heavy.

**Comment by doggy8088** [comment]
You don't have to scan all modules in the **node_modules** folder and sub-folders.  All you need to do is scan the packages with depth level 0 only ( `npm list --depth=0` ) and check for the `"schematics"` property in the `package.json`.  I don't think it's too heavy for most of the angular apps.

**Comment by cyrilletuzi** [comment]
Just tried: with `npm list depth=0`, there are indeed a reasonable quantity of packages, but just to launch the command, it already takes 5 seconds (as I suppose npm has to check the depth level). Then it would need to scan the remaining packages.

If we can defer the process, and ensure asynchronicity in every step, maybe there can be a way. But still, it should not be done each time the extension is launched, but I'm not sure what should be the trigger then...

**Comment by doggy8088** [comment]
The `npm list depth=0` might not the ideal case to find out all the possible depth=0 packages.  What I thought is really simple: 

1. List all the packages in `package.json` by just query it's json.  Just find out `devDependencies` packages.
2. Scan the `node_modules/PKGNAME/package.json` files and only look for `"schematics"` property in that file.  If yes, then it's very possible a schematics package.

Anyway, I think It's possible to provide additional VSCode command to detect all possible schematics packages rather than detect it on extension startup.

**Comment by cyrilletuzi** [comment]
Precisions:
- most schematics are in `dependencies`, not `devDependencies`;
- a detect button could be add in the Angular panel added by the lib.

I'll check that later, or feel free to do a PR.

**Comment by doggy8088** [comment]
It maybe most schematics are in `dependencies`, but it SHOULD be in `devDependencies` in my opinion.

**Comment by cyrilletuzi** [comment]
Defaults schematics have been refactored to be in a [simple file](https://github.com/cyrilletuzi/vscode-angular-schematics/blob/master/src/schematics/defaults.ts), which is mentioned in the README.

So it's now easy for any user to do a quick PR to add schematics.

So I'll close this issue.
