### ISSUE TITLE
Error on first component creation No valid Angular config file found for the chosen workspace. Add a "angular.json" file in your project with `{ "version": 1 }`

### ISSUE THREAD

**Issue by mcrodrig** [cyrilletuzi/vscode-angular-schematics#191]
# Checks before posting an issue

- [X] I have read all the extension's documentation (README and docs/TROUBLESHOOTING)
- [X] My project meets the requirements indicated in README
- [X] I launched `ng g component hello` in the *VS Code* Terminal inside my project, and it works
- [X] I looked at the extension's logs ("Angular Schematics" Output channel, second tab left to the Terminal), and tried to fix my project's configuration accordingly
- [X] I understand I am writing to a *human being*, doing this open source project on his *free* time
- [X] I will be involved in my own issue, by answering questions and informing if the issue is resolved

# Configuration

- VS Code version: 1.46.1
- Angular version (`ng version`):
Angular CLI: 9.1.9
Node: 12.18.0
OS: darwin x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.9
@angular-devkit/build-angular     0.901.9
@angular-devkit/build-optimizer   0.901.9
@angular-devkit/build-webpack     0.901.9
@angular-devkit/core              9.1.9
@angular-devkit/schematics        9.1.9
@angular/cli                      9.1.9
@ngtools/webpack                  9.1.9
@schematics/angular               9.1.9
@schematics/update                0.901.9
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
# Description of the issue

When creating a new component I got error 
[Info - 6:15:02 PM] Starting journey to generate a component.
[Info - 6:15:02 PM] Context path detected: resolving current workspace folder from it.
[Error - 6:15:02 PM] No valid Angular config file found for the chosen workspace. Add a "angular.json" file in your project with `{ "version": 1 }`

# How to reproduce the issue
Create a new project using ng new myproject
Add the project to the workspace
Right click the app folder and try to create a component.

**Comment by cyrilletuzi** [comment]
Thanks for the detailed issue, but as you can imagine, such an immediate issue on a such simple case would have been spotted before. There must be something specific in config or in steps done which is not right.

Given you have created `ng new myproject`, what folder exactly do you open in VS Code?

**Comment by mcrodrig** [comment]
I created a new project test and had no problem. Then I created a new project call xxx-xxxxxxxx-xx and I can reproduce again the problem. It looks it is related to the project name.

**Comment by cyrilletuzi** [comment]
Tried with exactly `xxx-xxxxxxxx-xx` and it works.
