### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by sashkr** [cyrilletuzi/vscode-angular-schematics#25]
I can't generate any angular file.
I tried to generate component:
![image](https://user-images.githubusercontent.com/1886953/49640620-bbb18d00-fa16-11e8-82d1-4715cc5e151c.png)

As you can see from the image above, it generates some error which I can't understand because of weird encoding.
I copied command's text and pasted it in terminal window. That's what i got:
![image](https://user-images.githubusercontent.com/1886953/49640774-13e88f00-fa17-11e8-99d5-3293e3a3baa8.png)
It is russian language. It says: '.' is not recognized as an internal or external command, operable program or batch file.

Angular Schematics version: 1.11.0
Windows 10 x64 Professional (Russian Language)

**Comment by sashkr** [comment]
It seems this can help with encoding:
[https://github.com/nodejs/node-v0.x-archive/issues/2190](url)

**Comment by cyrilletuzi** [comment]
@sashkr Thanks for reporting this issue.

It's not specific with Russian language, it's specific to Windows which have problems dealing with a relative command. Fixing this right now.

**Comment by cyrilletuzi** [comment]
Fixed in 1.11.1.

**Comment by cyrilletuzi** [comment]
@sashkr Please take some time to [star the extension on Visual Studio Code marketplace](https://marketplace.visualstudio.com/items?itemName=cyrilletuzi.angular-schematics). 👍
