### ISSUE TITLE
Right clicking and icon not working

### ISSUE THREAD

**Issue by RickSeta** [cyrilletuzi/vscode-angular-schematics#261]
# Checks before posting an issue

- [x] I have read all the extension's documentation (README and docs/TROUBLESHOOTING)
- [X] My project meets the requirements indicated in README
- [X] I launched `ng g component hello` in the *VS Code* Terminal inside my project, and it works
- [X] I looked at the extension's logs ("Angular Schematics" Output channel, second tab left to the Terminal), and tried to fix my project's configuration accordingly
- [X] I understand I am writing to a *human being*, doing this open source project on his *free* time
- [X] I will be involved in my own issue, by answering questions and informing if the issue is resolved

# Configuration

- VS Code version: 
- Angular version (`ng version`):
```
Angular CLI: 10.1.0
Node: 14.9.0
OS: win32 x64

Angular: 10.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.0
@angular-devkit/build-angular     0.1001.0
@angular-devkit/build-optimizer   0.1001.0
@angular-devkit/build-webpack     0.1001.0
@angular-devkit/core              10.1.0
@angular-devkit/schematics        10.1.0
@ngtools/webpack                  10.1.0
@schematics/angular               10.1.0
@schematics/update                0.1001.0
rxjs                              6.6.2
typescript
```
VS Code 1.48.2 

            

# Description of the issue

Right clicking doesn't show the extension options and i can't activate the icon on the side bar.
I tried evrything the troubleshooting suggests and found out that the 'ng g' command wasn't working, but the CLI commands in general were. So i looked up and found out that when terminal is at the app folder it works perfectly, creating the 3 files as it should.

But i don't wanna type everytime so i was wondering if there's anything im missing.
Thx for reading

**Comment by cyrilletuzi** [comment]
Hello, I'm not sure to understand your issue. So you say that doing `ng g component hello` directly in the VS Code Terminal does not work, but doing `cd src/app` and then `ng g component hello` works?

If that is right, it is not an extension issue, you should fix your project to make it work correctly with the Angular CLI first.

**Comment by cyrilletuzi** [comment]
I'm closing this issue for house-keeping, as there is no news. Feel free to comment and I'll reopen it.
