### ISSUE TITLE
Support for git submodules

### ISSUE THREAD

**Issue by AndreyWV** [cyrilletuzi/vscode-angular-schematics#278]
# Checks before posting an issue

- [x] I have read all the extension's documentation (README and docs/TROUBLESHOOTING)
- [x] My project meets the requirements indicated in README
- [x] I launched `ng g component hello` in the *VS Code* Terminal inside my project, and it works
- [x] I looked at the extension's logs ("Angular Schematics" Output channel, second tab left to the Terminal), and tried to fix my project's configuration accordingly
- [x] I understand I am writing to a *human being*, doing this open source project on his *free* time
- [x] I will be involved in my own issue, by answering questions and informing if the issue is resolved

# Configuration

- VS Code version: 1.49.2
- Angular version (`ng version`): global: 10.1.4, local: 8.3.29

# Description of the issue
If project has git submodule (library) with own `angular.json`, extension generates component in lib folder instead of project.

# How to reproduce the issue
Imitate project with git submodule:
```
$ ng new hello-world
$ mkdir hello-world/lib
$ ng new hello-world-lib
$ mv hello-world-lib/ hello-world/lib/
```
Then open project in vscode and in explorer select folder `hello-world/src/app` and chose `Angular: Generate a component`, print name `test`, press Enter.
New component locates in `hello-world/lib/hello-world-lib/src/app/`.

If generate component by ng-cli, component generates in correct folder:
```
cd hello-world/src/app/
ng g component test
```
Generates component in `hello-world/src/app/`

**Comment by cyrilletuzi** [comment]
Hi @AndreyWV,

Thanks for your full report.

Indeed, this is not a case I planned. Given that Angular already have a library feature (`ng g library`), which is very simpler than git submodules, what is your use case for preferring the second option?

I'll take a look when I have some time to see if it is a scenario easy to add.

**Comment by AndreyWV** [comment]
Hi @cyrilletuzi, the case is: I'm working now on large project and tons of legacy modules it use stored in other project (submodule - legacy project).

**Comment by cyrilletuzi** [comment]
Ok, I'll look into this, I think it should not be too difficult to implement.

**Comment by cyrilletuzi** [comment]
After investigation, I anticipated such a scenario by limiting the search of `angular.json` to 1 result. But I was supposing that VS Code was looking in a logical order (from root to subfolders), but apparently the whole search is asynchronous, so sometimes the first result is indeed the root `angular.json` and some other times not.

A fix is ready, I'll just let the weekend pass to check that with a fresh mind next week.

**Comment by cyrilletuzi** [comment]
@AndreyWV Support for git submodules has been added in 4.5.0.

For info: with more than 350 000 users, this extension is a lot of *non-paid* work. Yet I still do not have any **[sponsor](https://github.com/sponsors/cyrilletuzi)**. So please consider to help, or to ask your enterprise, which makes money with this extension, to help.
