### ISSUE TITLE
Support auto-detect of project with custom configurations

### ISSUE THREAD

**Issue by cyrilletuzi** [cyrilletuzi/vscode-angular-schematics#29]
Currently, the extension auto-detect the project (for librairies and multiples apps) if right-click was done inside the default CLI directory for that: `projects`.

It could use info in `angular.json` to support custom directories too.

**Comment by ibenjelloun** [comment]
When I try to generate a component in a library of a `@nrwl/schematics` workspace, the component is generated in the default app project. Is it related to this issue ?

**Comment by cyrilletuzi** [comment]
@ibenjelloun if the tool deviates from the default CLI directories structure (`/projects/*/src/lib` or `/projects/*/src/app`), then yes.

Support for custom configurations is coming soon, but for now you can still do it by choosing "Generate an advanced schematics" and using the `project` option.

**Comment by cyrilletuzi** [comment]
@ibenjelloun Released in v1.18.

Please take a few seconds to star it on [VS Code marketplace](https://marketplace.visualstudio.com/items?itemName=cyrilletuzi.angular-schematics). Unfortunately I don't get any official support, so this is the only way to make the extension known. 👍
