### ISSUE TITLE
path argument used for name / default argument

### ISSUE THREAD

**Issue by Lightw3ight** [cyrilletuzi/vscode-angular-schematics#31]
When you right click and select `Angular: Generate a component` the path you right clicked on is used to populate the first propt `Name or pathname`
The value of this prompt is then used as the _default_ argument, which according to the `schema.json` for the component schematic should be the `name` argument
```
"name": {
  "type": "string",
  "description": "The name of the component.",
  "$default": {
    "$source": "argv",
    "index": 0
  }
}
```
There is a separate argument for path defined in the `schema.json` that should be populated instead
```
    "path": {
      "type": "string",
      "format": "path",
      "description": "The path to create the component.",
      "visible": false
    }
```

I discovered this issue when trying to use one of my own schematics that uses the same setup, `name` as the default argument and `path` as a named argument.
If I want to make my schematic work with this extension then I would have to make `path` the default argument which dosent make much sense as it is optional

What would make more sense is to look thru the schema for an argument with `"format": "path"` and populate that with the path that the user right clicked on, then have a separate prompt for `name`

**Comment by cyrilletuzi** [comment]
Hi @Lightw3ight, thanks for caring about this extension.

This is the normal behavior of the CLI. As you can see in the code you showed, `path` is an invisible option, meaning this is not to be used directly by the user (and the extension never shows such options).

It's a tenable argument to say it's not consistent on a dev level, but it's very useful for the user to manage the two options at the same time. Anyway, it's not an extension made by this extension but by the CLI itself, and the extension must follow the CLI rules.

The best solution would be for your custom schematics to follow the same behavior as the CLI (there may even be an exported helper function from the schematics package that do the job for you).

But I'm open to see if there could be something specific to manage about your own schematics. But I'll need your schematics code to test.

Note that:
- if your own `path` option is not set as invisible, it will already be proposed by the extension,
- I was planning a refactoring, including the management of `argv` options: the extension may support more than one `argv`

**Comment by Lightw3ight** [comment]
Thanks @cyrilletuzi I will have a play around and a dig into how the angular ones do it.

Also, thanks for building this extension, I use schematics so much more now i can use them through your extension, its fantastic :D

**Comment by cyrilletuzi** [comment]
@Lightw3ight OK, closing this one for now then, but feel free to comment if there is anything new, and I will reopen the issue.

I'm glad you like the extension. Please take a few seconds to star it on [VS Code marketplace](https://marketplace.visualstudio.com/items?itemName=cyrilletuzi.angular-schematics). Unfortunately I don't get any official support, so this is the only way to make the extension known. 👍

**Comment by Lightw3ight** [comment]
Already have :D
