### ISSUE TITLE
OnPush Option does not work when creating component.

### ISSUE THREAD

**Issue by distante** [cyrilletuzi/vscode-angular-schematics#40]
I created a component named `TrainingOptions` using "Advanced Component", I marked it as *entry component*  and *change detection On Push*

The generated `ng` cli was: 

`ng g component components/config-menu/TrainingOptions --changeDetection OnPush --entryComponent`

The equal sign is missing here `-changeDetection OnPush` so the component was created without changeDetection

![image](https://user-images.githubusercontent.com/5490201/53679368-4a5b4080-3ccc-11e9-97b9-2e9ecfb5e911.png)

**Comment by cyrilletuzi** [comment]
@distante Thanks for your feedback.

The equal sign is not required, so it's not the problem here.

The only situation where I can reproduce your issue is with an outdated version of the CLI and having set a default for `changeDetection` in `angular.json`. But when it happens, it also happens directly with the CLI, so it's not an issue with this extension.

Can you:
- tell me your exact current version of the CLI?
- update your CLI and see if the issue is still here?
- confirm you hve this somewhere in your `angular.json`:
```json
{
  "schematics": {
    "@schematics/angular:component": {
      "changeDetection": "Default"
    }
  }
}
```

**Comment by distante** [comment]
Hi @cyrilletuzi 

I have version 7.3.3
```
Angular CLI: 7.3.3
Node: 10.14.1
OS: win32 x64
Angular: 7.2.6
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.3.3
@angular-devkit/schematics        7.3.3
@angular/cli                      7.3.3
@ngtools/webpack                  7.2.4
@schematics/angular               7.3.3
@schematics/update                0.13.3
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.28.4
```

About the schematics, I use it on an Ionic Project which uses : 
```
"cli": {
    "defaultCollection": "@ionic/angular-toolkit"
  },
```

but I override the options using:

```
  "schematics": {
    "@ionic/angular-toolkit:component": {
      "styleext": "scss",
      "changeDetection": "OnPush"
    },
    "@ionic/angular-toolkit:directive": {
      "styleext": "scss",
      "flat": false
    },
    "@ionic/angular-toolkit:page": {
      "styleext": "scss"
    },
    "@ionic/angular-toolkit:service": {
      "flat": false
    },
    "@ionic/angular-toolkit:pipe": {
      "flat": false
    }
  }
```

I have updated the cli to 7.3.4 with the same result. BUT as you said it happens also with the CLI, so I it is a problem with my environment (no idea where thought) .

**Comment by cyrilletuzi** [comment]
@distante As I was able to reproduce the issue in one case, the issue doesn't seem to be specific to your project, so once you isolate the problem, I would advise to open an issue in Angular CLI repo.

As it has consequences for this extension, please keep me in touch so I can follow.

**Comment by distante** [comment]
Hi @cyrilletuzi just to do an update. I still haven't found what exactly is the problem but I am able to reproduce this problem consistently.

If you creates (or clones) an [ionic project](https://www.npmjs.com/package/ionic) and after that updates the angular cli to the latest version the problems happens (if you do not updates the cli it does not recognize the `--changeDetection` flag

```
ionic start
npm install @angular/cli@7.3.4
ng g component Test --changeDetection=OnPush --entryComponent
```
