### ISSUE TITLE
Right clicking folder does not add path to command on Windows

### ISSUE THREAD

**Issue by andybond006** [cyrilletuzi/vscode-angular-schematics#416]
# Checks before posting an issue

- [x] I have read all the extension's documentation (README and docs/TROUBLESHOOTING)
- [x] My project meets the requirements indicated in README
- [x] I launched `ng g component hello` in the *VS Code* Terminal inside my project, and it works
- [x] I looked at the extension's logs ("Angular Schematics" Output channel, second tab left to the Terminal), and tried to fix my project's configuration accordingly
- [x] I understand I am writing to a *human being*, doing this open source project on his *free* time
- [x] I will be involved in my own issue, by answering questions and informing if the issue is resolved

# Configuration

- VS Code version: 1.53.0
- Angular version (`ng version`): 
```
Angular CLI: 11.1.2
Node: 12.18.4
OS: win32 x64

Angular: 11.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.2
@angular-devkit/build-angular   0.1101.2
@angular-devkit/core            11.1.2
@angular-devkit/schematics      11.1.2
@angular/cli                    11.1.2
@angular/flex-layout            11.0.0-beta.33
@schematics/angular             11.1.2
@schematics/update              0.1101.2
rxjs                            6.6.3
typescript                      4.1.3
```

# Description of the issue

Right-clicking a folder in the explorer tree and generating a service is not placing the generated service in the directory I clicked.

# How to reproduce the issue

Right-click a folder, generate a service, the command does not include the folder I clicked and generates the service in the module's folder (app) instead of app/services (where I right-clicked).

I only started noticing this issue today - so could be related to the new version that was just published today.

# Output Logs for Generating a Component Under Folder `app/settings`

```
[Info - 9:32:29 AM] Starting journey to generate a component.
[Info - 9:32:29 AM] Context path detected: resolving current workspace folder from it.
[Info - 9:32:29 AM] Workspace folder selected: "lrc-dashboard"
[Info - 9:32:29 AM] Full context path detected: /C:/Users/bond_a/Projects/Angular Projects/lrc-dashboard/src/app/settings
[Info - 9:32:29 AM] Workspace folder-relative context path detected: ../../../../../../C:/Users/bond_a/Projects/Angular Projects/lrc-dashboard/src/app/settings
[Info - 9:32:29 AM] No Angular project detected from context path.
[Info - 9:32:29 AM] Angular project used: "lrc-dashboard"
[Info - 9:32:29 AM] Collection used: "@schematics/angular"
[Info - 9:32:29 AM] Schematic used: "@schematics/angular:component"
[Info - 9:32:29 AM] This schematic has a default argument to set the path and name.
[Info - 9:32:29 AM] Context path detected for default argument: ""
[Info - 9:32:35 AM] You have canceled the generation.
```

**Comment by cyrilletuzi** [comment]
Hi, thanks for the detailed report.

v4.9 possibly messed with paths on Windows (it is a hell to manage correctly).

Your "Workspace folder-relative context path detected" log is anormal so there is definitively an issue. I'll look into it as soon as possible.

**Comment by andybond006** [comment]
Thanks! I really love the extension - so keep up the good work!

**Comment by cyrilletuzi** [comment]
Issue spotted. VS Code is inconsistently reporting the workspace path with `c:` or `C:` depending if you have only one project opened or you are in a multi-workspaces scenario.

Can you confirm you are in a multi-workspace setup? And that it is working normally if you just open only one project/folder?

**Comment by andybond006** [comment]
I am actually in a single workspace folder. The only other thing I can think of regarding my workspace that is different is that I use ESLint rather than TSLint. Happy to provide any more information you need, just let me know how I can help.

**Comment by cyrilletuzi** [comment]
@andybond006 v4.10.1 just released (and will be able via auto-update in a few minutes) should have fixed the issue. Can you confirm?

**Comment by andybond006** [comment]
@cyrilletuzi Looks like it is working properly now. Thanks!
