### ISSUE TITLE
Ensure files explorer refresh

### ISSUE THREAD

**Issue by cyrilletuzi** [cyrilletuzi/vscode-angular-schematics#42]
Usually, VS Code auto-refreshes the files explorer when files are created.

But sometimes it doesn't work, and it seems to happen more frequently in last version.

Would be nice if the extension can ensure this.

**Comment by cyrilletuzi** [comment]
Released in v1.21.

@smnbbrv Thanks for reporting.

**Comment by smnbbrv** [comment]
👍
