### ISSUE TITLE
project option not added if it's secondary project set as default

### ISSUE THREAD

**Issue by Lightw3ight** [cyrilletuzi/vscode-angular-schematics#44]
I have a solution with 4 projects

3 projects are in the projects folder
`/projects/[project-name]`
1 project is in the default location 
`/src`

The default project as configured in my `angular.json` file is one of the projects located in the `/projects` folder

If I right click on a folder located inside the **default** project which as stated above exists within the `/projects` folder and select one of the `Angular: Generate xxx` options everything appears to work fine **except** the end result never includes the `--project=xxx` argument.
With the outcome that the schematic is executed against the project located in `/src` and not the project I right clicked on

If I try the same on any other project in the `/projects` folder that is **not** the default project, it all works fine.

This is possibly more an issue on the CLI side where in that it always assumes the default project is `./src` if none is supplied, but it would be super usefull if this extension could always include the `--project=` flag for all projects that are not located inside `./src`

**Comment by cyrilletuzi** [comment]
According to angular/angular-cli#11111, this is the expected behavior from the CLI, and `defaultProject` may be deprecated.

I'll release a fix to adapt to this behavior, thanks for pointing this @Lightw3ight.

**Comment by cyrilletuzi** [comment]
Fixed in 1.22.

**Comment by Lightw3ight** [comment]
Awesome, thanks heaps, such a great extension :D
