### ISSUE TITLE
some problems in Windows10

### ISSUE THREAD

**Issue by ktrls** [cyrilletuzi/vscode-angular-schematics#48]
Hi, I installed these extension but I can able to use it.

If I click on the right button of the mouse on an empty folder there aren't extension choices.
Then I create a new app wit ng new <app name> and again no choices in the context menu.
I tried to use command by MVSC console (for example to create a component) but it say: command 'ngschematics.generateComponent' not found.

What is my error?

Some infos about the enviroment:

- I have made reboot of MVSC after installation of the extension
- I'm working on a workplace with 2 folders: the first contains a Java Maven project (the back-end of my project); in the second I would develop the front-end in Angular

Thanks in advance
KtrlS

**Comment by cyrilletuzi** [comment]
Hi. As stated in the "Requirements" chapter of README:

> **The project opened must be the root directory of the Angular project. It won't work from a parent directory, as the CLI itself requires to be in the Angular directory.**
> 
> If your Angular project is inside your backend project, and you want both opened in VS Code:
> - open the root directory of the Angular project,
> - then in VS Code menu: "File" > "Add Folder to Workspace" > open the directory of your backend project.

If it wasn't the problem, just tell me and I'll reopen the issue.

**Comment by ktrls** [comment]
I read the requirements and I don't know if I have done right or wrong.
When I began the project I created an empty workspace and added the backend project. Then I have created the Angular folder and added too.

If I understand your suggestion I have to create a new workspace from the Angular folder and afte that add the backend project.

I have tried now but nothing changes

Sorry but this is my first experience with Angular and even with MVSC.

Thanks a lot

**Comment by cyrilletuzi** [comment]
The order of the projects doesn't matter. You should have 2 folders opened *in the same workspace* with one of them being the *root* directory of your Angular project (ie. with `angular.json` at the root of the folder). And *not* 2 different VS Code *windows*.

[Official doc of VS Code multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces)

**Comment by ktrls** [comment]
ok, I don't know where is my trouble but seems that I make the right way.

This is my situation now

![immagine](https://user-images.githubusercontent.com/8734356/57192045-7e511d00-6f2c-11e9-8f36-eee7279b4a18.png)

**Comment by cyrilletuzi** [comment]
OK it's just because your Angular config file doesn't have the good name, so the extension activation is not trigerred. It should be:
- `.angular-cli.json` (with a dot) in Angular < 6 projects
- `angular.json` in Angular >= 6 projects

**Comment by ktrls** [comment]
ok, I have checked my Angular version and was an old version. So I have renewed Angular and Angular-cli and then all is ok.

Thanks you for your patience and your precious help

Bye
Salvo
