### ISSUE TITLE
Support Yarn/npm workspaces

### ISSUE THREAD

**Issue by victorschinaider** [cyrilletuzi/vscode-angular-schematics#49]
In my project, i'm using `yarn` workspaces.
It's my folder structure:

```
- api (subproject  - folder)
- app (subproject - folder)
- models (subproject - folder)
package.json
yarn.lock
```

When yarn is using workspaces, it creates a node_module folder at root directory with almost all dependencies of subprojects. Extensions is not identifying this behavior.

PS.: Realize that app (the project that has angular framework) has your own `package.json`, so it's the root directory too.

**Comment by cyrilletuzi** [comment]
Currently, as stated in README, it's a requirement to open the Angular project as the root dir:

> **The project opened must be the root directory of the Angular project. It won't work from a parent directory, as the CLI itself requires to be in the Angular directory.**
> 
> If your Angular project is inside your backend project, and you want both opened in VS Code:
> - open the root directory of the Angular project,
> - then in VS Code menu: "File" > "Add Folder to Workspace" > open the directory of your backend project.

This is a VS Code extension, so *VS Code* workspaces should be used to open your yarn workspaces.

But is a direct usage of Angular CLI working with your configuration? Last time I tested, the CLI itself required to be in the root directory.

If the CLI supports it, adding support for yarn workspaces could be an enhancement but I have no time for this (and no personal interest for yarn to be honest), so a PR is welcomed. Be aware that the extension does a lot of path detection, so adding this feature would require a lot of changes and a lot of tests to be sure it still works in all scenarios.

**Comment by victorschinaider** [comment]
@cyrilletuzi , i perfectly undestand.
If i open the "app" directory as root, it not works too.

**Comment by cyrilletuzi** [comment]
Is `angular.json` present at the root of the `app` project?

And is a direct usage of Angular CLI (from the terminal) working with your initial configuration?

**Comment by victorschinaider** [comment]
> Is `angular.json` present at the root of the `app` project? 
> And is a direct usage of Angular CLI (from the terminal) working with your initial configuration?

Yes for both questions.

**Comment by victorschinaider** [comment]
I see the code superficially, so i maybe be wrong.

```typescript
static getNodeModulesPath(cwd: string, ...paths: string[]) {
   return path.join(cwd, 'node_modules', ...paths);
}
```
Are you searching for parent `node_modules` folders, as specified in NodeJs specs?
https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders

**Comment by andreialecu** [comment]
Monorepos are a quite common pattern and yarn workspaces are the most common tool for the job.

The Angular CLI works without problem with yarn workspaces.

I think this extension could just search for an `angular.json` within the nearest parent folder instead of the root. Other extensions, such as `vscode-eslint` properly understand eslint configurations within various directories and know to run the proper eslint package with separate settings based on which workspace directory they belong to.

**Comment by cyrilletuzi** [comment]
> Monorepos are a quite common pattern

Agree.

> yarn workspaces are the most common tool for the job.

Pure assumption. Angular CLI provides an official way to do monorepos, and it's *not* with yarn workspaces (`ng new --createApplication false`, and then `ng g application` for each new project).

> I think this extension could just search for an angular.json within the nearest parent folder instead of the root. Other extensions, such as vscode-eslint properly understand eslint configurations within various directories and know to run the proper eslint package with separate settings based on which workspace directory they belong to.

Sure. Never said it's not possible or that I was opposed to this feature. As the issue label says: "help wanted". A PR or at least pointing to the code in `vscode-eslint` that allows to manage this feature is very welcome. ;)

**Comment by andreialecu** [comment]
I think it's common to have an angular project and perhaps a backend project such as one made with NestJS.

Regarding vscode-eslint, some references:
https://github.com/Microsoft/vscode-eslint#mono-repository-setup

https://github.com/microsoft/vscode-eslint/blob/98079ad1a31a85bb8b8d0c6d1faa048318ff2a61/client/src/extension.ts
Search for `workingDirectories`

**Comment by cyrilletuzi** [comment]
@victorschinaider @andreialecu I've tried an implementation in #126, but I need real world testing as I'm not a Yarn user myself. Instructions in the Pull Request.

**Comment by cyrilletuzi** [comment]
For info: v4.0 (released soon) partially fixes this issue as the extension is now looking in parent directories to find the `node_modules` folder.

So it will work in this scenario (ie. when at at least 2 projects of the workspace are Angular ones, so the Angular dependencies are shared):
```
- workspace
  - node_modules
    - @schematics/angular
  - angular-project1
  - angular-project2
```

But it will *not* work yet in this scenario (ie. when only one project in the workspace is an Angular one, so the Angular dependencies are scoped):
```
- workspace
  - node_modules
    - angular-project
      - @schematics/angular
  - angular-project
  - vue-project
```

The latest scenario may be supported in v4.x if someone do the testing required in #126.

**Comment by cyrilletuzi** [comment]
@andreialecu Thanks for all the help! I finally installed Yarn to see by myself and it was simpler than expected. I was reluctant on infinite lookup but it doesn't seem to impact performances even if there is no `node_modules` anywhere.

v4.0.0-beta.7 fixes this issue, instructions to test in #125

**Comment by andreialecu** [comment]
Not sure what I'm doing wrong, I installed `v4.0.0-beta.7` but the context menu isn't showing the schematic commands. It did before, while I was using this PR directly.

**Comment by andreialecu** [comment]
Nevermind, it reverted to 3.3.1 for some reason.

**Comment by andreialecu** [comment]
Alright, confirmed that a simple service was created in the right folder in an actual complex production project, good job @cyrilletuzi. 🚀 

Thanks for this!

**Comment by cyrilletuzi** [comment]
For info: v4 has just been released and is a full rewrite of the extension. Hoisted `node_modules`, and thus Yarn workspaces, are now supported.

It took more than a *full-time* non-paid week to do this rewrite. Yet I still do not have any **[sponsor](https://github.com/sponsors/cyrilletuzi)**. So please consider to help, or to ask your enterprise, which makes money with this extension, to help.
