### ISSUE TITLE
Adding community new schematics

### ISSUE THREAD

**Issue by Dj-jom2x** [cyrilletuzi/vscode-angular-schematics#53]
like if there's *-routing.module.ts  inside where you right click.. it will auto add there.. or have an option to do it? :) btw this is nice plugin

**Comment by cyrilletuzi** [comment]
Hi, thanks for your feedback.

This extension is just *using* schematics, it doesn't add new ones or modify the existing ones.

Supplement this extension with community schematics would be a nice idea, but it would need a lot of time that I doesn't have now. It would also need some rules to know which schematics we accept or not.

**Comment by cyrilletuzi** [comment]
Closing this one as it would be another project and it's already possible to add your own schematics.
