### ISSUE TITLE
Extension not working when the Angular project is in a subdirectory

### ISSUE THREAD

**Issue by cyrilletuzi** [cyrilletuzi/vscode-angular-schematics#7]
Normally, when you open your Angular project, it is the root directory.

But if you open a parent directory as the project (for example, if you have your Angular project inside your back-end project), the extension doesn't work.

**Comment by cyrilletuzi** [comment]
After investigation, it's the normal behavior, as `ng g` command itself needs to be in root directory. Adding instructions in README.

**Comment by awarche** [comment]
at least there should be error message. not just a silent nothing

**Comment by cyrilletuzi** [comment]
@awarche Feel free to submit a Pull Request. At least README should be read.
