### ISSUE TITLE
Problem with word "app" appearing twice in path

### ISSUE THREAD

**Issue by gbrugiere** [cyrilletuzi/vscode-angular-schematics#87]
(on Windows)
Hi Cyrille,
In our company, we put our projects in subdirectories within an "app" directory. We have created a new Angular project, we have a problem using the wizard.

I.e. : the new project is in a `D:\workspace\app\ourCustomer\ourProject\web\angularProject`.
Triing to create a new component with right clicking in `D:\workspace\**app**\ourCustomer\ourProject\web\angularProject\src\**app**\features` shows a directory `ourCustomer\ourProject\web\angularProject\src\` at first step. We have to delete everything here and type a correct path. The next steps of wizard are OK.

**Comment by cyrilletuzi** [comment]
@gbrugiere Thanks for the report.

Fixed in v2.3.2.
