### ISSUE TITLE
[6.10.1 & 6.11.0] Blocked by MacAfee malware detected

### ISSUE THREAD

**Issue by cyrilletuzi** [cyrilletuzi/vscode-angular-schematics#929]
### Discussed in https://github.com/cyrilletuzi/vscode-angular-schematics/discussions/928

<div type='discussions-op-text'>

<sup>Originally posted by **UnleashSpirit** August  2, 2024</sup>
Hi,

I try to update to 6.10.1 but the MacAfee Web Gateway of my company is blocking the download cause of virus detection.

Virus Name: JS/Downloader.eu
File Name: cyrilletuzi.angular-schematics-6.10.1.vsix

I got no problem to download 6.10.0 verison
</div>

**Comment by cyrilletuzi** [comment]
From the [discussion](https://github.com/cyrilletuzi/vscode-angular-schematics/discussions/928):

Given how the extension is built, it sometimes happens that it results into false positives in some anti-virus softwares.

Problem is: it happens randomly and it is not an issue on my machines (Mac and a Windows machine where Microsoft Defender is OK). Until now, VS Code marketplace, which does its own anti-virus detection, was flagging the problematic builds, but it was OK this time.

I will look into a solution, until then v6.10.0 is totally fine, v6.10.1 was just an internal fix with no user facing changes.

If someone knows an online MacAfee service to scan a file, it would help a lot.

**Comment by cyrilletuzi** [comment]
@UnleashSpirit any chance with v6.11.1?

**Comment by UnleashSpirit** [comment]
Yes 6.11.1 works !

**Comment by cyrilletuzi** [comment]
I found a solution to detect the issue before publishing, so it should not happen again.
