### ISSUE TITLE
Project definition could not be found

### ISSUE THREAD

**Issue by Dj-jom2x** [cyrilletuzi/vscode-angular-schematics#93]
seems creating service doesnt ask anything and nothing happen and if you create component this message shows

`"The generate command requires to be run in an Angular project, but a project definition could not be found."`

**Comment by cyrilletuzi** [comment]
As stated in the changelog, there was no code change in v3.0, it was just a bump of minimal VS Code and Angular versions requirements. So it's highly unlikely that v3.0 is the issue.

I tested (again), and it works well both in Angular 8 and 9, and both on Mac and Windows. So:
- did it worked with v2.x?
- the error message is quite explicit, so do your workspace meet the requirements stated in the README, ie:
  - being at the root of the project,
  - being in an Angular CLI project, ie. with a `angular.json` file at root?

**Comment by Dj-jom2x** [comment]
v2 is fine.. but I update it :( I always do update it

**Comment by cyrilletuzi** [comment]
Closing this issue for house-keeping, as there is no news. Feel free to comment with more info and I'll reopen it.

**Comment by cyrilletuzi** [comment]
For info: v4 has just been released and is a full rewrite of the extension. It should have fixed all weird cases like this one.

It took more than a *full-time* non-paid week to do this rewrite. Yet I still do not have any **[sponsor](https://github.com/sponsors/cyrilletuzi)**. So please consider to help, or to ask your enterprise, which makes money with this extension, to help.

**Comment by alicezelberg** [comment]
I have the same problem. I updated the angular CLI just to be sure that's not a problem. Can anyone help and explain why this happens? I created a project somehow and I am in the root folder so why suddenly it stopped working
